### ISSUE TITLE
How stable is MathC version 2?

### ISSUE THREAD

**Issue by Nairou** [ferreiradaselva/mathc#24]
From what I can tell, v2 looks a lot friendlier than v1. v1 has been around a while, but v2 is listed as in development. Is it still recommended to use v1? Or is v2 ready for use in projects?

**Comment by felselva** [comment]
Version 2 is _mostly_ ready, and the one I recommend (I use in my own projects, too).

In v2, operations with euler angles are still untested and incomplete. But, you can use quaternions, which are working since v1. Everything else is stable, as far as I can tell, and the **possible** incompatibility changes until the stable release are:

- Deprecate `vec*_scale()` and `quat_scale()` in favor of `vec*_multiply_*()` and `quat_multiply_f()`.
- Some functions might be renamed for better consistency. Example: `mat4_rotation_quat` and `quat_from_mat4` are conversion functions, but only one of them has `_from_` in the name. I might remove the `_from_`.

**Comment by Nairou** [comment]
Perfect! Thank you!
