### ISSUE TITLE
Function to apply translation to existing mat4?

### ISSUE THREAD

**Issue by Nairou** [ferreiradaselva/mathc#25]
When building a camera transform matrix, I have a quaternion for the heading and a vec3 for the camera position. I can use smat_rotation_quat() to build the rotation matrix from the quaternion, but then I need to insert the position as well. I don't see any functions for this, all mat4 translate functions appear to build a new mat4 from scratch.

For reference, I'm converting from linmath.h which had mat4x4_translate_in_place().

**Comment by felselva** [comment]
Yeah, there's no function for that.

Since I'm deprecating `*_scale` (will be changed to `_multiply_f`), I could reuse this verb, as well "translate" and "rotate" to add functions that increment on matrices already built:

New matrices from scratch:
- `mat4_scaling`
- `mat4_translation`
- `mat4_rotation`

Increment on matrices already built:
- `mat4_scale`
- `mat4_translate`
- `mat4_rotate*`

Increment scale and translation will be easy, but rotation will require more work, since there are rotations with multiple types (increment rotation using other matrix/quat/euler/axis).

**Comment by felselva** [comment]
For example, is this what you need?

```c
/* Build from scratch */
mfloat_t *mat4_translation(mfloat_t *result, mfloat_t *v)
{
	result[0] = MFLOAT_C(1.0);
	result[1] = MFLOAT_C(0.0);
	result[2] = MFLOAT_C(0.0);
	result[3] = MFLOAT_C(0.0);
	result[4] = MFLOAT_C(0.0);
	result[5] = MFLOAT_C(1.0);
	result[6] = MFLOAT_C(0.0);
	result[7] = MFLOAT_C(0.0);
	result[8] = MFLOAT_C(0.0);
	result[9] = MFLOAT_C(0.0);
	result[10] = MFLOAT_C(1.0);
	result[11] = MFLOAT_C(0.0);
	result[12] = v[0];
	result[13] = v[1];
	result[14] = v[2];
	result[15] = MFLOAT_C(1.0);
	return result;
}

/* Increment on existing matrix */
mfloat_t *mat4_translate(mfloat_t *result, mfloat_t *m, mfloat_t *v)
{
	result[12] = m[12] + v[0];
	result[13] = m[13] + v[1];
	result[14] = m[14] + v[2];
	return result;
}
```

**Comment by felselva** [comment]
**They already can be tested in the branch `mathc2`:https://github.com/ferreiradaselva/mathc/commit/8729135a6c48b0423bf0b19aac6b901455744cb0.**

I did some research, and it seems the usual case is to build the matrix from scratch from vectors/quaternion and then multiply them (rotation * scale * translate)[1]. So, I'm not sure if this is something 100% correct to do. But it might be usefult in some cases, nevertheless.

Functions for rotating existing matrices will take a while longer to make, as I explained above.

[1] Example of what I do:

```c
mfloat_t view[MAT4_SIZE];
mfloat_t projection[MAT4_SIZE];
mfloat_t projection_view[MAT4_SIZE];

mat4_look_at(view, position, target, up);
mat4_ortho(projection,
	-WINDOW_WIDTH * 0.5f, WINDOW_WIDTH * 0.5f,
	-WINDOW_HEIGHT * 0.5f, WINDOW_HEIGHT * 0.5f,
	0.1f, 2.0f);
mat4_multiply(projection_view, projection, view);
/* Then I can send `projection_view` to the shader */
```

If you do the model matrix on the client-side, instead of on the shader, this is an example of how a model matrix can be done:

```c
mfloat_t position_mat[MAT4_SIZE];
mfloat_t scale_mat[MAT4_SIZE];
mfloat_t rotation_mat[MAT4_SIZE];
mfloat_t model_scale_mat[MAT4_SIZE];
mfloat_t model_mat[MAT4_SIZE];

/* Make each matrix */
mat4_translation(position_mat, position);
mat4_scaling(scale_mat, scale);
mat4_rotation_z(rotation_mat, to_radians(angle));

/* The following order of multiplications depends on what you want to accomplish: */
mat4_multiply(model_mat, scale_mat, position_mat);
mat4_multiply(model_mat, model_mat, rotation_mat);

/* If you are working with the model matrix on client-side, this is how we transform
the points p0-p3 of our quad:
p0      /p2
|     /  |
|   /    |
p1/      p3 */
vec4_multiply_mat4(p0, p0, model_mat);
vec4_multiply_mat4(p1, p1, model_mat);
vec4_multiply_mat4(p2, p2, model_mat);
vec4_multiply_mat4(p3, p3, model_mat);
/* You can send the points to the OpenGL buffer */
```

**Comment by Nairou** [comment]
That was fast!

Yes, building a view matrix from a quaternion rotation and vector position is my intended use. I was even thinking you could shortcut the process by having a single function do both steps.

However, it wouldn't have to do any more than that, as I keep view and projection separate, and send both to the shader.
